In [1]:
import numpy as np
import pandas as pd
!pip install wooldridge

     |████████████████████████████████| 5.1 MB 5.2 MB/s 


In [59]:
import wooldridge as wd

In [60]:
crime=wd.data("crime1")

In [61]:
crime=crime[["narr86","pcnv","avgsen","tottime","inc86"]]

In [62]:
crime

narr86  pcnv     avgsen    tottime       inc86
0          0  0.38  17.600000  35.200001    0.000000
1          2  0.44   0.000000   0.000000    0.800000
2          1  0.33  22.799999  22.799999    0.000000
3          2  0.25   0.000000   0.000000    8.800000
4          1  0.00   0.000000   0.000000    8.100000
...      ...   ...        ...        ...         ...
2720       1  0.00   0.000000   0.000000    0.000000
2721       0  0.00   0.000000   0.000000   11.500000
2722       0  0.00   0.000000   0.000000    1.900000
2723       1  0.00   0.000000   0.000000    0.000000
2724       0  0.00   0.000000   0.000000  191.300003

[2725 rows x 5 columns]

In [63]:
Pr=crime.pop("narr86")

In [64]:
Kom=np.c_[np.ones(len(crime)),crime.to_numpy()]

In [65]:
Kom

array([[  1.        ,   0.38      ,  17.60000038,  35.20000076,
          0.        ],
       [  1.        ,   0.44      ,   0.        ,   0.        ,
          0.80000001],
       [  1.        ,   0.33000001,  22.79999924,  22.79999924,
          0.        ],
       ...,
       [  1.        ,   0.        ,   0.        ,   0.        ,
          1.89999998],
       [  1.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
        191.30000305]])

In [66]:
Pr

0       0
1       2
2       1
3       2
4       1
       ..
2720    1
2721    0
2722    0
2723    1
2724    0
Name: narr86, Length: 2725, dtype: int64

In [67]:
class regresion:
  def __init__(self,Kom,Pr):
    self.Kom=Kom
    self.Pr=Pr
  def betas(self):
    b=np.linalg.inv(Kom.T@x)@(Pr.T@y)
    return St

In [69]:
def errorest(h):
  h=(Kom.T)*betas

In [71]:
Kom.shape

(2725, 5)

In [74]:
Pr=Pr.values.reshape(-1,1)

In [78]:
St=np.linalg.inv(Kom.T@Kom)@(Kom.T@Pr)

In [79]:
St

array([[ 0.59387489],
       [-0.16243696],
       [-0.00618803],
       [ 0.00771062],
       [-0.00243615]])

In [80]:
yestim=Kom@St

In [81]:
errorestim=Pr-yestim

In [82]:
n,k=Kom.shape

In [83]:
varianza=(errorestim.T@errorestim)/(n-k)

In [84]:
(varianza*np.linalg.inv(Kom.T@Kom)).shape

(5, 5)

In [85]:
np.diagonal(varianza*np.linalg.inv(Kom.T@Kom))

array([6.68620927e-04, 1.66595309e-03, 1.53282544e-04, 8.89626197e-05,
       5.91487773e-08])

In [86]:
errorestandar=(np.diagonal(varianza*np.linalg.inv(Kom.T@Kom)))**(1/2)

In [90]:
St

array([[ 0.59387489],
       [-0.16243696],
       [-0.00618803],
       [ 0.00771062],
       [-0.00243615]])

In [91]:
errorestandar

array([0.02585771, 0.04081609, 0.01238073, 0.009432  , 0.00024321])

In [92]:
def betass(Kom,Pr):
  b=np.linalg.inv(Kom.T@Kom)@(Kom.T@Pr)
  return St

In [93]:
def ee(Kom,Pr):
  errorestandar=(np.diagonal(varianza*np.linalg.inv(Kom.T@Pr)))**(1/2)
  return errorestandar

In [103]:
betaet=betass(Kom,Pr)

In [97]:
estadisticot=(betaet)/eeet

In [98]:
estadisticot

array([[ 22.9670375 ],
       [ -3.97972866],
       [ -0.49981111],
       [  0.81749603],
       [-10.01685265]])

In [99]:
limsup=betaet+1.96*eeet

In [100]:
liminf=betaet-1.96*eeet

In [101]:
limsup

array([[ 0.64455599],
       [-0.08243742],
       [ 0.01807821],
       [ 0.02619734],
       [-0.00195947]])

In [102]:
liminf

array([[ 0.54319379],
       [-0.24243649],
       [-0.03045426],
       [-0.0107761 ],
       [-0.00291283]])

In [107]:
class regresion:
  def __init__(self,Kom,Pr):
    self.Kom=Kom
    self.Pr=Pr
  def betas(self):
    b=np.linalg.inv(self.Kom.T@self.Kom)@(self.Kom.T@self.Pr)
    return St
  def ee(self):
    errorestandar=(np.diagonal(varianza*np.linalg.inv(self.Kom.T@self.Kom)))**(1/2)
    return errorestandar.reshape(-1,1)
  def estadisticot(self):
    estadisticot=((self.betas())/self.ee())
    return estadisticot
  def intervaloconfianza(self):
    limsup=self.betas()+1.96*self.ee()
    liminf=self.betas()-1.96*self.ee()
    for i, j in zip(liminf, limsup):
      print(i[0], j[0])
    

In [108]:
reg=regresion(Kom,Pr)

In [109]:
reg.betas()

array([[ 0.59387489],
       [-0.16243696],
       [-0.00618803],
       [ 0.00771062],
       [-0.00243615]])

In [110]:
reg.ee()

array([[0.02585771],
       [0.04081609],
       [0.01238073],
       [0.009432  ],
       [0.00024321]])

In [111]:
reg.estadisticot()

array([[ 22.9670375 ],
       [ -3.97972866],
       [ -0.49981111],
       [  0.81749603],
       [-10.01685265]])

In [112]:
reg.intervaloconfianza()

0.5431937864640133 0.6445559915485397
-0.24243649161581132 -0.08243742400040029
-0.030454264059060702 0.018078208443667927
-0.010776097183979797 0.026197341926345832
-0.0029128330429314983 -0.0019594685942179017


In [113]:
import wooldridge as wd

In [114]:
crime2=wd.data("crime1")

In [115]:
crime2=crime2[["narr86","pcnv","avgsen","tottime","inc86","pcnvsq","inc86sq"]]

In [116]:
crime2

narr86  pcnv     avgsen    tottime       inc86  pcnvsq       inc86sq
0          0  0.38  17.600000  35.200001    0.000000  0.1444      0.000000
1          2  0.44   0.000000   0.000000    0.800000  0.1936      0.640000
2          1  0.33  22.799999  22.799999    0.000000  0.1089      0.000000
3          2  0.25   0.000000   0.000000    8.800000  0.0625     77.440002
4          1  0.00   0.000000   0.000000    8.100000  0.0000     65.610008
...      ...   ...        ...        ...         ...     ...           ...
2720       1  0.00   0.000000   0.000000    0.000000  0.0000      0.000000
2721       0  0.00   0.000000   0.000000   11.500000  0.0000    132.250000
2722       0  0.00   0.000000   0.000000    1.900000  0.0000      3.610000
2723       1  0.00   0.000000   0.000000    0.000000  0.0000      0.000000
2724       0  0.00   0.000000   0.000000  191.300003  0.0000  36595.691406

[2725 rows x 7 columns]

In [117]:
Pr=crime2.pop("narr86")

In [118]:
Kom=np.c_[np.ones(len(crime2)),crime2.to_numpy()]

In [119]:
Kom

array([[1.00000000e+00, 3.79999995e-01, 1.76000004e+01, ...,
        0.00000000e+00, 1.44400001e-01, 0.00000000e+00],
       [1.00000000e+00, 4.39999998e-01, 0.00000000e+00, ...,
        8.00000012e-01, 1.93599999e-01, 6.40000045e-01],
       [1.00000000e+00, 3.30000013e-01, 2.27999992e+01, ...,
        0.00000000e+00, 1.08900011e-01, 0.00000000e+00],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.89999998e+00, 0.00000000e+00, 3.60999990e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.91300003e+02, 0.00000000e+00, 3.65956914e+04]])

In [120]:
Pr

0       0
1       2
2       1
3       2
4       1
       ..
2720    1
2721    0
2722    0
2723    1
2724    0
Name: narr86, Length: 2725, dtype: int64

In [121]:
def errorest2(h):
  h=(Kom.T)*betas

In [122]:
Kom.shape

(2725, 7)

In [123]:
Pr=Pr.values.reshape(-1,1)

In [129]:
Br=np.linalg.inv(Kom.T@Kom)@(Kom.T@Pr)

In [131]:
Br

array([[ 5.77523688e-01],
       [ 6.22634460e-01],
       [-6.92546885e-03],
       [ 4.48874198e-03],
       [-4.08083748e-03],
       [-8.26588291e-01],
       [ 8.56614968e-06]])

In [126]:
Pr

array([[0],
       [2],
       [1],
       ...,
       [0],
       [1],
       [0]])

Cuando la proporcion de cadenas aumentar provoca que la cantidad de veces que esta persona sea arrestado se reduzca.
Se puede observar que cuando los ingresos salariales que se reciben son altos, las personas tienen menos probabilidades de estar bajo aresto, sin embargo las personas que reciben poca o no tienen remuneracion son proclives a estar bajo ese sesgo de estar arrestados.